CREATE TABLE IF NOT EXISTS schema_migrations (id TEXT PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, mobile_number TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS movies (id INTEGER PRIMARY KEY, title TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS theatres (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS movie_theatres (movie_id INTEGER NOT NULL REFERENCES movies(id), theatre_id INTEGER NOT NULL REFERENCES theatres(id), PRIMARY KEY (movie_id,theatre_id));
CREATE TABLE IF NOT EXISTS bookings (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), movie_id INTEGER NOT NULL REFERENCES movies(id), theatre_id INTEGER NOT NULL REFERENCES theatres(id), seats TEXT NOT NULL, payment_method TEXT NOT NULL CHECK(payment_method IN ('CARD','UPI')), total_price INTEGER NOT NULL CHECK(total_price=450), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
